name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout go
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Build
        run: go build .
        env:
          GOPROXY: 'https://proxy.golang.org'

      - name: Test
        run: go test ./...
        env:
          GOPROXY: 'https://proxy.golang.org'
